//-----------------------------------------------------------------------
// <copyright file=" d_target_car.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_target_car.cs
// * history : Created by T4 07/04/2019 10:24:10
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_target_car Entity Model
    /// </summary>   
    [Serializable]
    public class d_target_car
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 车名
        /// </summary>
        public string Name { get; set; }
   
        /// <summary>
        /// 照片
        /// </summary>
        public string ImagePath { get; set; }
   
        /// <summary>
        /// 车牌号
        /// </summary>
        public string CarID { get; set; }
   
        /// <summary>
        /// 安全级别
        /// </summary>
        public int SecurityLevelID { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public DateTime UpdateTime { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int RecStatus { get; set; }
    }
}
