//-----------------------------------------------------------------------
// <copyright file=" d_alarm_info.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_alarm_info.cs
// * history : Created by T4 07/04/2019 10:24:10
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_alarm_info Entity Model
    /// </summary>   
    [Serializable]
    public class d_alarm_info
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 报警内容
        /// </summary>
        public string Content { get; set; }
   
        /// <summary>
        /// 报警时间
        /// </summary>
        public DateTime AlarmTime { get; set; }
   
        /// <summary>
        /// 报警类别ID
        /// </summary>
        public int AlarmTypeID { get; set; }
   
        /// <summary>
        /// 报警设备ID
        /// </summary>
        public int AlarmDeviceID { get; set; }
   
        /// <summary>
        /// 视频记录
        /// </summary>
        public string VedioRecrdPath { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public DateTime UpdateTime { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int RecStatus { get; set; }
    }
}
