//-----------------------------------------------------------------------
// <copyright file=" a_user.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: a_user.cs
// * history : Created by T4 07/04/2019 10:24:10
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// a_user Entity Model
    /// </summary>   
    [Serializable]
    public class d_duty
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }

        /// <summary>
        /// 班次
        /// </summary>
        public string Class { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShaoWei1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShaoWei2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShaoWei3 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShaoWei4 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShaoWei5 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShaoWei6 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShaoWei7 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShaoWei8 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShaoWei9 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShaoWei10 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShaoWei11 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShaoWei12 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShaoWei13 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShaoWei14 { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public DateTime UpdateTime { get; set; }
        /// <summary>
        /// 执行时间
        /// </summary>
        public string ExcutionTime { get; set; }

    }
}
