//-----------------------------------------------------------------------
// <copyright file=" a_data_access.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: a_data_access.cs
// * history : Created by T4 06/26/2019 18:47:56
// </copyright>
//-----------------------------------------------------------------------
using SqlSugar;
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// a_data_access Entity Model
    /// </summary>   
    [SugarTable("a_data_access")]
    public class a_data_access
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public string Name { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public string Description { get; set; }
    }
}
