//-----------------------------------------------------------------------
// <copyright file=" a_ui_access_type.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: a_ui_access_type.cs
// * history : Created by T4 07/04/2019 10:24:10
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// a_ui_access_type Entity Model
    /// </summary>   
    [Serializable]
    public class a_ui_access_type
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public string Name { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public string Description { get; set; }
    }
}
