//-----------------------------------------------------------------------
// <copyright file=" ar_user_ui_access.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: ar_user_ui_access.cs
// * history : Created by T4 06/26/2019 18:47:56
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// ar_user_ui_access Entity Model
    /// </summary>   
    [Serializable]
    public class ar_user_ui_access
    {
        /// <summary>
        /// 
        /// </summary>
        public int UserID { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int UiAccessID { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int UiAccessTypeID { get; set; }
    }
}
