//-----------------------------------------------------------------------
// <copyright file=" ar_usergroup_user.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: ar_usergroup_user.cs
// * history : Created by T4 07/04/2019 10:24:10
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// ar_usergroup_user Entity Model
    /// </summary>   
    [Serializable]
    public class ar_usergroup_user
    {
        /// <summary>
        /// 
        /// </summary>
        public int UserGroupID { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int UserID { get; set; }
    }
}
