//-----------------------------------------------------------------------
// <copyright file=" d_camera_group.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_camera_group.cs
// * history : Created by T4 06/26/2019 18:47:56
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_camera_group Entity Model
    /// </summary>   
    [Serializable]
    public class d_camera_group
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 名称
        /// </summary>
        public string Name { get; set; }
   
        /// <summary>
        /// 节点类型
        /// </summary>
        public int NodeType { get; set; }
   
        /// <summary>
        /// 父节点ID
        /// </summary>
        public int ParentID { get; set; }
    }
}
