//-----------------------------------------------------------------------
// <copyright file=" d_pap_arsenal.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_pap_arsenal.cs
// * history : Created by T4 07/04/2019 10:24:10
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_pap_arsenal Entity Model
    /// </summary>   
    [Serializable]
    public class d_pap_arsenal
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 仓库名
        /// </summary>
        public string Name { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int DepartmentID { get; set; }
   
        /// <summary>
        /// 备注
        /// </summary>
        public string Description { get; set; }
   
        /// <summary>
        /// 经度
        /// </summary>
        public double Longitude { get; set; }
   
        /// <summary>
        /// 维度
        /// </summary>
        public double Latitude { get; set; }
   
        /// <summary>
        /// 高程
        /// </summary>
        public double Altitude { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string Guid { get; set; }
        /// <summary>
        /// 是否删除
        /// </summary>
        public bool IsDeleted { get; set; }
    }
}
