//-----------------------------------------------------------------------
// <copyright file=" d_phone_table.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_phone_table.cs
// * history : Created by T4 06/26/2019 18:47:56
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_phone_table Entity Model
    /// </summary>   
    [Serializable]
    public class d_phone_table
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 通联表名称
        /// </summary>
        public string Name { get; set; }
   
        /// <summary>
        /// 通联表类型
        /// </summary>
        public int PhoneTableTypeID { get; set; }
   
        /// <summary>
        /// 单位
        /// </summary>
        public int DepartmentID { get; set; }
   
        /// <summary>
        /// 图片路径
        /// </summary>
        public string ImagePath { get; set; }
   
        /// <summary>
        /// 更新时间
        /// </summary>
        public DateTime UpdateTime { get; set; }
    }
}
