//-----------------------------------------------------------------------
// <copyright file=" d_shaowei_arrange.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_shaowei_arrange.cs
// * history : Created by T4 07/04/2019 10:24:10
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_shaowei_arrange Entity Model
    /// </summary>   
    [Serializable]
    public class d_shaowei_arrange
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 哨兵
        /// </summary>
        public int SoildierID { get; set; }
   
        /// <summary>
        /// 哨位
        /// </summary>
        public int ShaoweiID { get; set; }
   
        /// <summary>
        /// 描述
        /// </summary>
        public DateTime Deacription { get; set; }
   
        /// <summary>
        /// 上哨时间
        /// </summary>
        public DateTime StartTime { get; set; }
   
        /// <summary>
        /// 下哨时间
        /// </summary>
        public DateTime EndTime { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public DateTime UpdateTime { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int RecStatus { get; set; }
   
        /// <summary>
        /// 提前时间
        /// </summary>
        public int AdvanceTime { get; set; }
   
        /// <summary>
        /// 延后时间
        /// </summary>
        public int DelayTime { get; set; }
   
        /// <summary>
        /// 排班表名
        /// </summary>
        public string ScheduleName { get; set; }
   
        /// <summary>
        /// 当班士兵
        /// </summary>
        public string DutySoildier { get; set; }
   
        /// <summary>
        /// 值班时间
        /// </summary>
        public string DutyTime { get; set; }
    }
}
