//-----------------------------------------------------------------------
// <copyright file=" d_shaowei_check.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_shaowei_check.cs
// * history : Created by T4 07/04/2019 10:24:10
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_shaowei_check Entity Model
    /// </summary>   
    [Serializable]
    public class d_shaowei_check
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 查哨人
        /// </summary>
        public int SoldierID { get; set; }
   
        /// <summary>
        /// 哨位
        /// </summary>
        public int ShaowenPlanID { get; set; }
   
        /// <summary>
        /// 描述
        /// </summary>
        public string Description { get; set; }
   
        /// <summary>
        /// 查哨时间
        /// </summary>
        public DateTime CheckTime { get; set; }
   
        /// <summary>
        /// 视频
        /// </summary>
        public string VideoPath { get; set; }
    }
}
