//-----------------------------------------------------------------------
// <copyright file=" d_shaowei_preplan.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_shaowei_preplan.cs
// * history : Created by T4 06/26/2019 18:47:56
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_shaowei_preplan Entity Model
    /// </summary>   
    [Serializable]
    public class d_shaowei_preplan
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 预案名称
        /// </summary>
        public string Name { get; set; }
   
        /// <summary>
        /// 哨位
        /// </summary>
        public int ShaowenID { get; set; }
   
        /// <summary>
        /// 图片路径
        /// </summary>
        public string ImagePath { get; set; }
   
        /// <summary>
        /// 更新时间
        /// </summary>
        public DateTime UpdateTime { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int RecStatus { get; set; }
    }
}
