//-----------------------------------------------------------------------
// <copyright file=" d_shaowei_arrange.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_shaowei_arrange.cs
// * history : Created by T4 06/26/2019 18:47:56
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_shaowei_arrange Entity Model
    /// </summary>   
    [Serializable]
    public class d_shaowei_arrange
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 哨兵
        /// </summary>
        public int SoildierID { get; set; }
   
        /// <summary>
        /// 哨位
        /// </summary>
        public int ShaoweiID { get; set; }
   
        /// <summary>
        /// 描述
        /// </summary>
        public string Deacription { get; set; }
   
        /// <summary>
        /// 上哨时间
        /// </summary>
        public DateTime StartTime { get; set; }
   
        /// <summary>
        /// 下哨时间
        /// </summary>
        public DateTime EndTime { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public DateTime UpdateTime { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int RecStatus { get; set; }
    }
}
