//-----------------------------------------------------------------------
// <copyright file=" d_soldier_train.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_soldier_train.cs
// * history : Created by T4 07/04/2019 10:24:10
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_soldier_train Entity Model
    /// </summary>   
    [Serializable]
    public class d_soldier_train
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int SoldierID { get; set; }
   
        /// <summary>
        /// 描述
        /// </summary>
        public string Description { get; set; }
   
        /// <summary>
        /// 学习/培训地点
        /// </summary>
        public string Place { get; set; }
   
        /// <summary>
        /// 离队时间
        /// </summary>
        public DateTime LeaveTime { get; set; }
   
        /// <summary>
        /// 归队时间
        /// </summary>
        public DateTime ReturnTime { get; set; }
   
        /// <summary>
        /// 计划离队时间
        /// </summary>
        public DateTime PlanLeaveTime { get; set; }
   
        /// <summary>
        /// 计划归队时间
        /// </summary>
        public DateTime PlanReturnTime { get; set; }
   
        /// <summary>
        /// 批准人
        /// </summary>
        public string AuthorizeMan { get; set; }
   
        /// <summary>
        /// 登记人
        /// </summary>
        public string RecordMan { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public DateTime UpdateTime { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int RecStatus { get; set; }
    }
}
