//-----------------------------------------------------------------------
// <copyright file=" d_soldier.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_soldier.cs
// * history : Created by T4 07/04/2019 10:24:10
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_soldier Entity Model
    /// </summary>   
    [Serializable]
    public class d_soldier
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 姓名
        /// </summary>
        public string Name { get; set; }
   
        /// <summary>
        /// 照片
        /// </summary>
        public string ImagePath { get; set; }
   
        /// <summary>
        /// 军人证号
        /// </summary>
        public string SoldierID { get; set; }
   
        /// <summary>
        /// 入伍日期
        /// </summary>
        public string InductedDay { get; set; }
   
        /// <summary>
        /// 退伍日期
        /// </summary>
        public string LeaveDay { get; set; }
   
        /// <summary>
        /// 出生日期
        /// </summary>
        public string Birthday { get; set; }

        /// <summary>
        /// 民族ID
        /// </summary>
        public int Nation { get; set; }
   
        /// <summary>
        /// 籍贯
        /// </summary>
        public string NativePlace { get; set; }
   
        /// <summary>
        /// 警衔
        /// </summary>
        public int PoliceRankID { get; set; }
   
        /// <summary>
        /// 职务
        /// </summary>
        public int PostID { get; set; }
   
        /// <summary>
        /// 性别
        /// </summary>
        public string Gender { get; set; }
   
        /// <summary>
        /// 健康状况
        /// </summary>
        public int HealthID { get; set; }
   
        /// <summary>
        /// 在位状态
        /// </summary>
        public int SoilderStateID { get; set; }
   
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime UpdateTime { get; set; }
   
        /// <summary>
        /// 记录状态
        /// </summary>
        public int RecStatus { get; set; }

        /// <summary>
        /// 婚姻状态
        /// </summary>
        public int IsMarriageID { get; set; }

        /// <summary>
        /// 教育程度
        /// </summary>
        public int EducationID { get; set; }

        /// <summary>
        /// 政治面貌
        /// </summary>
        public int PoliticalRoleID { get; set; }
        /// <summary>
        /// 地址
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 联系人
        /// </summary>
        public string Contact { get; set; }

        //public string Unit { get; set; }
    }
}
