//-----------------------------------------------------------------------
// <copyright file=" d_target_people_whitelist.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_target_people_whitelist.cs
// * history : Created by T4 06/26/2019 18:47:56
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_target_people_whitelist Entity Model
    /// </summary>   
    [Serializable]
    public class d_target_people_whitelist
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 人员
        /// </summary>
        public int TargetPeopleID { get; set; }
   
        /// <summary>
        /// 登记人
        /// </summary>
        public string RecordMan { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public DateTime UpdateTime { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int RecStatus { get; set; }
    }
}
