//-----------------------------------------------------------------------
// <copyright file=" d_target_people.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_target_people.cs
// * history : Created by T4 07/04/2019 10:24:10
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_target_people Entity Model
    /// </summary>   
    [Serializable]
    public class d_target_people
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 姓名
        /// </summary>
        public string Name { get; set; }
   
        /// <summary>
        /// 照片
        /// </summary>
        public string ImagePath { get; set; }
   
        /// <summary>
        /// 人员类别
        /// </summary>
        public int TargetPeopleTypeID { get; set; }
   
        /// <summary>
        /// 安全级别
        /// </summary>
        public int SecurityLevelID { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int RecStatus { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public DateTime UpdateTime { get; set; }
   
        /// <summary>
        /// 来访事由
        /// </summary>
        public string Visreason { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Guid { get; set; }
        /// <summary>
        /// 是否删除
        /// </summary>
        public bool IsDeleted { get; set; }
    }
}
