//-----------------------------------------------------------------------
// <copyright file=" d_target_camera_record_car.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_target_camera_record_car.cs
// * history : Created by T4 07/04/2019 10:24:10
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_target_camera_record_car Entity Model
    /// </summary>   
    [Serializable]
    public class d_target_camera_record_car
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 车辆信息
        /// </summary>
        public int CarID { get; set; }
   
        /// <summary>
        /// 名称
        /// </summary>
        public string Name { get; set; }
   
        /// <summary>
        /// 时间
        /// </summary>
        public DateTime RecTime { get; set; }
   
        /// <summary>
        /// 抓拍照片
        /// </summary>
        public string ImagePath { get; set; }

        /// <summary>
        /// 车牌类型
        /// </summary>
        public string PlateType { get; set; }

        /// <summary>
        /// 车辆类型
        /// </summary>
        public string CarType { get; set; }

        /// <summary>
        /// 车辆颜色
        /// </summary>
        public string CarColor { get; set; }

        /// <summary>
        /// 汽车品牌
        /// </summary>
        public string CarLogo { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public int RecStatus { get; set; }
    }
}
