//-----------------------------------------------------------------------
// <copyright file=" d_target_camera_record_people.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: d_target_camera_record_people.cs
// * history : Created by T4 07/04/2019 10:24:10
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// d_target_camera_record_people Entity Model
    /// </summary>   
    [Serializable]
    public class d_target_camera_record_people
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int PeopleID { get; set; }
   
        /// <summary>
        /// 名称
        /// </summary>
        public string Name { get; set; }
   
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime RecTime { get; set; }
   
        /// <summary>
        /// 抓拍照片
        /// </summary>
        public string ImagePath { get; set; }
        /// <summary>
        /// 相似度
        /// </summary>
        public int Similar { get; set; }

        /// <summary>
        /// 地点
        /// </summary>
        public string Position { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public int RecStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Guid { get; set; }
        /// <summary>
        /// 是否删除
        /// </summary>
        public bool IsDeleted { get; set; }
               /// <summary>
        /// 
        /// </summary>
        public string HandleID { get; set; }
    }
}
