//-----------------------------------------------------------------------
// <copyright file=" dr_arsenal_equipment.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: dr_arsenal_equipment.cs
// * history : Created by T4 06/26/2019 18:47:56
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// dr_arsenal_equipment Entity Model
    /// </summary>   
    [Serializable]
    public class dr_arsenal_equipment
    {
        /// <summary>
        /// 
        /// </summary>
        public int ArsenalID { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int EquipmentID { get; set; }
    }
}
