//-----------------------------------------------------------------------
// <copyright file=" dr_cameragroup_camera.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: dr_cameragroup_camera.cs
// * history : Created by T4 06/26/2019 18:47:56
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Tuby.Api.Model
{
    /// <summary>
    /// dr_cameragroup_camera Entity Model
    /// </summary>   
    [Serializable]
    public class dr_cameragroup_camera
    {
        /// <summary>
        /// 
        /// </summary>
        public int CameraGroupID { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public int CameraID { get; set; }
    }
}
